### ISSUE TITLE
Way to Require Condition #1 (require number) OR Condition #2 (require special character)

### ISSUE THREAD

**Issue by machineghost** [mapbox/password-rules#8]
First off, thanks for making a library that was (almost) exactly what I was looking for!

However, one improvement that would be nice is the ability to require only one of several conditions. 
Currently I can use the following options to specify "require ALL of these things":

    { requireCapital: true, requireLower: true, requireNumber: true, requireSpecial: true }

That's great if you're a banking site.  However, if you're running a less secure site there's no way to specify "require ONE OF these things".  It'd be great if I could somehow specify that "one of" (or "two of") a set of requirements is required, eg.:

    { requireCapital: 1, requireLower: true, requireNumber: 1, requireSpecial: 1 }
    // allows:  "foo123" or "fooABC" or "foo!!!"

    // alternatively ...
    { requireCapital: 2, requireLower: true, requireNumber: 2, requireSpecial: 2 }
    // allows: "foo123!!!", "fooABC123", or "fooABC!!!"

Not a huge deal, but for my site it would be nice if there was an easy way that I could give my users a choice of (say) capitals or numbers.

**Comment by jeffastorey** [comment]
Stale, closing
